import type { Metadata } from "next"
import { Roboto } from "next/font/google"
import 'app/sass/globals.sass'
import { Header } from "app/components/shared/Header"
import { Footer } from "app/components/shared/Footer"

const roboto = Roboto({
  weight: ['100', '400', '500', '700'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "My Store",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es">
      <body className={roboto.className}>
        <Header />
        <div className='globalContainer'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
